import "./globals.css";
import { play } from "./utils/fonts";
import "aos/dist/aos.css";

import Navbar from "./components/navbar/page";
import Footer from "./components/footer/page";

export const metadata = {
  title: "Galaxi Carpet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={play.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
